### ISSUE TITLE
How do I capture live data from the sensor?

### ISSUE THREAD

**Issue by karansaxena** [Qirky/PyKinectTk#2]

**Comment by Qirky** [comment]
Go into the ex-capture.py file and change the following line:

`App.listen(getVideo=True, Clicking=True, duration=120)`

to just

`App.listen()`

If the sensor is connected correctly then just running this script should start recording data. If you're interested in recording data just for playback then it might be better to just use the Kinect Studio V2.

**Comment by karansaxena** [comment]
Can I pass Live data to Quantity of Motion?

Alternatively, I have continuous 1080x1920x4 (RGBA) numpy nd arrays from frames from Kinect. Can I directly pass this to the QoM?

Thanks for being helpful.
